---
- hosts: service-api
  become: yes
  roles:
    - anperez78.sshkeys

- hosts: database
  become: yes
  roles:
    - anperez78.postgresql

- hosts: frontend
  become: yes
  roles:
    - anperez78.sshkeys
    - anperez78.nodejs
